- scripts/dev_server.sh
- scripts/skyhopper_daemon.sh
> Update booting scripts.

- app/assets/javascripts/infrastructures.js
- app/controllers/infrastructures_controller.rb
- app/controllers/nodes_controller.rb
- app/controllers/serverspecs_controller.rb
- app/helpers/application_helper.rb
- app/jobs/periodic_serverspec_job.rb
- app/models/infrastructure_log.rb
- app/models/serverspec_schedule.rb
- app/views/nodes/show.jbuilder
- app/views/vue/_ec2_tabpane.html.erb
- app/views/vue/_serverspec_tabpane.html.erb
- config/locales/en.yml
- config/locales/ja.yml
* Serverspec を任意の時間毎に実行できるようにした
* セキュリティアップデートの数を Yum ボタンに表示するようにした
* スケジュールされた Serverspec を実行する前にインスタンスが起動しているかチェックするようにした
* フォームのバリデーションを厳密にした
* uneditable input を disabled:no_entry_sign: から readonly に変更
* Resource 削除の際に、ResourceStatus や ServerspecSchedule が削除されない問題を修正
> some features

- app/assets/javascripts/infrastructures.js
- app/views/infrastructures/index.html.erb
- config/locales/en.yml
- config/locales/ja.yml
https://skyarch.backlog.jp/view/NC-498
> [NC-498] Display loading when accessing infra#index

- app/assets/javascripts/infrastructures.js
- config/locales/en.yml
https://www.sideci.com/github_repositories/31754199/issues/pull_request/21/all/c503a251#jshint
> fixed jshint problems and modifed en.yml

- Gemfile
- Gemfile.lock
- app/assets/javascripts/infrastructures.js
- app/assets/javascripts/modules/getURL.js
- app/assets/javascripts/modules/listen.js
- app/assets/javascripts/modules/loadindex.js
- app/assets/javascripts/modules/wrap.js
- app/assets/javascripts/projects.js
- app/controllers/projects_controller.rb
- app/helpers/projects_helper.rb
- app/views/infrastructures/index.html.erb
- app/views/projects/index.html.erb
- app/views/projects/index.json.jbuilder
- app/views/vue/_index.html.erb
- config/locales/en.yml
- config/locales/ja.yml
- frontend/package.json
- node_modules
1. Added Browserify to modularize the filters and other functionalities needed for searchable list in vue.
2. Implement search, sorting and pagination in project list.
3. Implement search, sorting and pagination in infrastructure list (Modularized).
4. UI wrap up to index files of projects page.
> Project list index javascript implementation.

- app/assets/javascripts/serverspecs.js
- app/controllers/serverspecs_controller.rb
- app/policies/serverspec_policy.rb
- app/views/serverspecs/generator.html
- app/views/serverspecs/generator.html.erb
- app/views/serverspecs/index.html.erb
- config/locales/en.yml
- config/locales/ja.yml
- config/routes.rb
- frontend/src/serverspec-gen/ast.ts
- frontend/src/serverspec-gen/ui.ts
- frontend/tsconfig.json
> [WIP] Serverspec Generator

- app/assets/javascripts/dishes.js
- app/assets/javascripts/modules/listen.js
- app/assets/javascripts/modules/wrap.js
- app/controllers/dishes_controller.rb
- app/views/dishes/index.html.erb
- app/views/dishes/index.json.jbuilder
- config/locales/en.yml
- config/locales/ja.yml
- spec/controllers/dishes_controller_spec.rb
* Sorting
* Searching
* Pagination
Please Merge PR when you are done reviewing it. Thanks!
> Applied SSP for Dishes Indexpage.

- app/assets/javascripts/cf_templates.js
- app/assets/javascripts/dishes.js
- app/assets/javascripts/modules/listen.js
- app/assets/javascripts/modules/wrap.js
- app/controllers/cf_templates_controller.rb
- app/helpers/cf_templates_helper.rb
- app/views/cf_templates/index.html.erb
- app/views/cf_templates/index.json.jbuilder
* Sorting
* Searching
* Pagination
Please Merge PR after reviewing. Thanks!
> Applied SSP for cf_templates indexpage.

- app/views/users_admin/index.html.erb
- app/views/vue/_user_admin_index.html.erb
- config/locales/en.yml
- config/locales/ja.yml
https://skyarch.backlog.jp/view/NC-510#comment-1125208708
> [WIP] Search user scope

- app/views/vue/_index.html.erb
- app/views/vue/_user_admin_index.html.erb
Please include this to the next release: 
To prevent search functionality from submitting when enter key is pressed. thanks!
> [Hotfix] Search enter btn

- app/controllers/infrastructures_controller.rb
- app/models/key_pair.rb
- config/locales/en.yml
- config/locales/ja.yml
- spec/controllers/infrastructures_controller_spec.rb
Please let me know if you have comments in this PR. and we'll merge it after doing so. Thanks!
> [WIP] Validation for keypair submission

- app/controllers/infrastructures_controller.rb
Hotfix for infrasturcure index page. pagination
> [Hotfix] infras#Index

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/infrastructures.js
- app/assets/javascripts/libraries.js
- app/views/vue/_add_modify_tabpane.html.erb
> [WIP] Syntax light

- app/assets/javascripts/cf_templates.js
- app/assets/javascripts/clients.js
- app/assets/javascripts/dishes.js
- app/assets/javascripts/infrastructures.js
- app/assets/javascripts/projects.js
- app/assets/javascripts/serverspecs.js
- app/assets/javascripts/user_index.js
Disable ajax request from saving the JSON/DATA to the browser's cache on index pages.
To avoid users from seeing the JSON Data when hitting Back or Front Button from their browsers.
> [Hotifx] Hide JSON 

- frontend/package.json
- frontend/src/users_admin.ts
- frontend/tsconfig.json
- frontend/tsd.json
> Update TypeScript to 1.6.2

- app/assets/javascripts/infrastructures.js
- app/assets/javascripts/libraries.js
- app/assets/stylesheets/application.css
- bower.json
- vendor/assets/javascripts/microplugin.js
- vendor/assets/javascripts/selectize.js
- vendor/assets/javascripts/sifter.js
- vendor/assets/stylesheets/selectize.paper.css
Use Selectize.js when selecting AWS region for creating/editing a new infrastructure.
> Selectize.js for keypair

- app/controllers/monitorings_controller.rb
- app/models/zabbix.rb
- config/locales/en.yml
- config/locales/ja.yml
PR is for 
https://skyarch.backlog.jp/view/NC-526
> fix error message to make it clear and precise

- Gemfile
- Gemfile.lock
- http://stackoverflow.com/questions/32457657/rails-4-gemloaderror-specified-mysql2-for-database-adapter-but-the-gem-i
- https://github.com/brianmario/mysql2/issues/675
> MySQL gem downgrade to 0.3.20

- circle.yml
Move dependency / test commands from Circle CI web UI to config file.
> Improve CircleCI setting

- app/assets/javascripts/projects.js
Fixed to apply Query-string API functionality to project.js
> [HOTFIX]  for project index: added querytring

- app/models/chef_api.rb
- app/models/node.rb
- lib/erb-builder/templates/chef_server.json.erb
- spec/models/node_spec.rb
Reverts skyarch-networks/skyhopper#67
> Revert "Chef bootstrap without the Internet"

- doc/installation/skyhopper.md
As metioned on. https://skyarch.backlog.jp/view/NC-535
> [HOTFIX] for npm version.

- app/controllers/elb_controller.rb
This is tiny fix.
I'll merge it after pass test
> Add trailing comma

- doc/installation/skyhopper.md
I'll merge this once test is done.
> tiny document change

- app/assets/javascripts/infrastructures.js
Forgot to add.
Please Review and Merge PR. once done. Thanks!
> [HOTFIX] for show#infra button

- Gemfile
- Gemfile.lock
Please Merge PR after test is done. @root-beer Thanks!. :bow:
> version down for ridley

- app/assets/javascripts/infrastructures.js
- app/assets/javascripts/modules/wrap.js
- app/views/vue/_operation_sched_tabpane.html.erb
- config/locales/en.yml
- config/locales/ja.yml
* searchable
* table sorting
* pagination
> Operation Scheduler SSP

- app/views/serverspecs/_gen_resource.html.erb
- frontend/src/serverspec-gen/ast.ts
- frontend/src/serverspec-gen/resource-panel.ts
- frontend/test/serverspec-gen/ast_test.ts
Ref: KIG_I-456
Please review and merge it :bow: @root-beer
> Trim empty argument in serverspec generator.

- app/assets/javascripts/infrastructures.js
- app/controllers/monitorings_controller.rb
- app/models/zabbix.rb
- app/views/infrastructures/_show.html.erb
- app/views/monitorings/show.jbuilder
- app/views/vue/_edit_monitoring_tabpane.html.erb
- config/locales/en.yml
- config/locales/ja.yml
- frontend/src/models/monitoring.ts
REFS: 
https://skyarch.backlog.jp/view/NC-566        
https://skyarch.backlog.jp/view/NC-568
##GOAL for this PR:
Please Review and Merge PR. @pocke .  Thanks!.   :bow:
> Zabbix Templates improve

- .travis.yml
- Procfile
- app/controllers/serverspecs_controller.rb
- app/models/serverspec.rb
- app/models/serverspec_info.rb
- app/views/serverspecs/_gen_it.html.erb
- app/views/serverspecs/_gen_resource.html.erb
- app/views/serverspecs/_gen_selectable_input.html
- app/views/serverspecs/generator.html.erb
- bin/serverspec_daemon.rb
- frontend/src/serverspec-gen/it-panel.ts
- frontend/src/serverspec-gen/resource-panel.ts
- frontend/src/serverspec-gen/selectable-input.ts
- frontend/src/serverspec-gen/serverspec_info.ts
- frontend/src/serverspec-gen/ui.ts
- frontend/tsconfig.json
- frontend/tslint.json
- spec/controllers/serverspecs_controller_spec.rb
- spec/models/serverspec_info_spec.rb
- spec/models/serverspec_spec.rb
NC-560
- Can use argument for matcher when select matcher.
- I think implement the above next PR.
memos
------
- delegate 
- http://maeshima.hateblo.jp/entry/20101031/1288539329
- http://stackoverflow.com/questions/14568211/in-rails-how-can-i-delegate-to-a-class-method
- druby
- http://docs.ruby-lang.org/ja/2.2.0/library/drb.html
- RSpec
- exists https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/exist-matcher
> Improve Serverspec generator(Select matcher/its_target)

- app/models/node.rb
This is a minor change. I'll merge this once test is done.
> remove puts on node.rb

- frontend/src/modal.ts
NC-557
I think this PR is small, so, I'll merge this if test is passed
> Escape error message.

- app/controllers/resources_controller.rb
- app/models/ec2_instance.rb
- spec/controllers/resources_controller_spec.rb
Ref: https://skyarch.backlog.jp/view/NC-569
> [WIP] NC-569

- app/assets/javascripts/infrastructures.js
- app/controllers/ec2_instances_controller.rb
- app/models/resource.rb
- app/views/infrastructures/modal/_modal_detach_ec2.html.erb
- frontend/src/models/ec2_instance.ts
> Optional Detach

- Gemfile
- Gemfile.lock
- app/assets/javascripts/infrastructures.js
- app/assets/stylesheets/application.css
- app/controllers/ec2_instances_controller.rb
- app/helpers/application_helper.rb
- app/policies/ec2_instance_policy.rb
- app/views/infrastructures/_resource_tabs.html.erb
- app/views/infrastructures/_show.html.erb
- app/views/layouts/_navbar_top.html.erb
- app/views/users_admin/index.html.erb
- app/views/vue/_add_ec2_tabpane.html.erb
- app/views/vue/_ec2_tabpane.html.erb
- app/views/vue/_index.html.erb
- config/routes.rb
- frontend/src/models/ec2_instance.ts
ref: https://skyarch.backlog.jp/view/NC-577
> selectable ec2 from AWS

- Gemfile
- Gemfile.lock
Downgrade sidekiq because I can't run my instance. 
I'll merge this once done. Thanks.
> downgrade sidekiq

- app/assets/javascripts/key_pairs.js
- app/views/key_pairs/index.html.erb
ref: https://skyarch.backlog.jp/view/NC-422
Improvement of keypair management
Please review and Merge PR: @root-beer . :bow:
> Keypair improve

- app/views/vue/_monitoring_tabpane.html.erb
* Fix missing statements
Please review and merge PR: @Joeper214 . Thanks! :bow:
> Fix Zabbix url status

- config/environments/production.rb
> Disable eager_load at production environment

- Gemfile
- Gemfile.lock
- circle.yml
- frontend/src/users_admin.ts
ref: https://skyarch.backlog.jp/view/NC-583.
Please review and merge PR. @root-beer .
Also, thank you for reporting this issue. :bow:
> import user index to fix bug

- app/views/vue/_elb_tabpane.html.erb
ref: https://skyarch.backlog.jp/view/NC-584
Please review and merge PR. @root-beer. :bow:
> NC-584 reported bug.

- Gemfile
- Gemfile.lock
- app/assets/javascripts/libraries.js
- app/views/infrastructures/index.html.erb
Please review and merge PR. @root-beer . :bow:
> added xray-rails debugging

- app/assets/javascripts/cf_templates.js
- app/assets/javascripts/clients.js
- app/assets/javascripts/infrastructures.js
- app/assets/javascripts/modules/listen.js
- app/assets/javascripts/projects.js
- app/assets/javascripts/serverspecs.js
- app/assets/javascripts/user_index.js
- app/assets/stylesheets/bootstrap_extend.css
- app/views/clients/index.html.erb
- app/views/vue/_index.html.erb
- app/views/vue/_user_admin_index.html.erb
> No results messaging during search on index pages

- app/assets/javascripts/libraries.js
- app/assets/stylesheets/application.css
- bower.json
- vendor/assets/javascripts/offline.min.js
- vendor/assets/stylesheets/offline-language-english.css
- vendor/assets/stylesheets/offline-theme-chrome.css
UI Helper when there is no internet connection. 
ref: http://github.hubspot.com/offline/
> Offline-mode

- frontend/package.json
- frontend/src/serverspec-gen.ts
@root-beer please review and merge it :bow:
https://github.com/skyarch-networks/serverspec-generator/commit/50ef2e272d2d08ace105bd421f67a76f30a797ce
> Update serverspec-generator npm

- lib/tasks/release.rake
Ref: https://skyarch.backlog.jp/view/NC-576
Usage
-------
```sh
bundle exec rake release:note_gen
```
> Release note generate task

- config/environments/production.rb
@root-beer please merge and review it :bow:
Refs
---
- https://skyarch.backlog.jp/view/NC-586
- https://skyarch.backlog.jp/view/NC-582
> Fast precompile

- app/assets/javascripts/modules/listen.js
- app/helpers/application_helper.rb
Ref: https://skyarch.backlog.jp/view/NC-574
@Joeper214 please review and merge it :bow:
> Gravatar with https

- bower.json
- frontend/package.json
- vendor/assets/javascripts/bootstrap.js
- vendor/assets/javascripts/lodash.js
- vendor/assets/javascripts/vue.js
> Bye bower welcome npm

- .travis.yml
I'll merge this myself if test isn't broken
> Remove unneeded test script

- public/fonts/glyphicons-halflings-regular.eot
- public/fonts/glyphicons-halflings-regular.svg
- public/fonts/glyphicons-halflings-regular.ttf
- public/fonts/glyphicons-halflings-regular.woff
- public/fonts/glyphicons-halflings-regular.woff2
Ref: #163 
@root-beer  Please review and merge it :bow:
> Can't find glyphicons 

- frontend/gulpfile.js
I'll merge PR when test is done.
> removed karma server from gulpfile

- frontend/package.json
https://github.com/skyarch-networks/serverspec-generator/releases/tag/v1.0.0
> Update servrspec generator npm

- config/initializers/01_monkeypatch.rb
Before
------
After
------
@Joeper214 please review and merge it :bow:
> Hide API key when unauthorized.

- app/controllers/users_admin_controller.rb
- app/models/user.rb
- spec/models/user_spec.rb
> MFA with issuer.

- app/assets/javascripts/infrastructures.js
- app/assets/javascripts/libraries.js
- app/controllers/cf_templates_controller.rb
- app/models/cf_template.rb
- app/models/project_parameter.rb
- app/views/project_parameters/show.jbuilder
- app/views/vue/_insert_cf_params.html.erb
- config/locales/en.yml
- config/locales/ja.yml
- frontend/package.json
- frontend/src/complete_project_parameter.ts
- frontend/tsconfig.json
- spec/models/project_parameter_spec.rb
- vendor/assets/javascripts/jquery.textcomplete.js
> Project parameter for Cloudformation template

- config/database_default.yml
> In test env, use sqlite3 as default.

- app/assets/javascripts/infrastructures.js
- app/controllers/nodes_controller.rb
- app/helpers/infrastructures_helper.rb
- app/views/vue/_edit_attr_tabpane.html.erb
- app/views/vue/_insert_cf_params.html.erb
- frontend/src/complete_project_parameter.ts
> In cook, use Project Parameter

- config/initializers/logger.rb
[Logging · celluloid/celluloid Wiki](https://github.com/celluloid/celluloid/wiki/Logging)
I'll merge it after test pass
> Update celluroid logger.

- Procfile
- bin/sidekiq
Sidekiq Jobs does not work well when using spring in Sidekiq.
> Use spring in rails only

- app/assets/javascripts/infrastructures.js
- app/assets/javascripts/infrastructures/add-ec2-tabpane.js
- app/assets/javascripts/infrastructures/cf-history-tabpane.js
- app/assets/javascripts/infrastructures/ec2-tabpane.js
- app/assets/javascripts/infrastructures/edit-monitoring-tabpane.js
- app/assets/javascripts/infrastructures/elb-tabpane.js
- app/assets/javascripts/infrastructures/helper.js
- app/assets/javascripts/infrastructures/infra-logs-tabpane.js
- app/assets/javascripts/infrastructures/monitoring-tabpane.js
- app/assets/javascripts/infrastructures/operation-sched-tabpane.js
- app/assets/javascripts/infrastructures/rds-tabpane.js
- app/assets/javascripts/infrastructures/s3-tabpane.js
`current_infra`がglobalに露出していないため、`alert_and_show_infra`が動かない。
まだ直していない。
> infra.js bugfix

- app/assets/javascripts/infrastructures.js
- app/assets/javascripts/infrastructures/ec2-tabpane.js
- app/assets/javascripts/libraries.js
- app/assets/javascripts/share.js
- app/helpers/vue_helper.rb
- bower.json
- frontend/package.json
- vendor/assets/javascripts/ZeroClipboard.js
- vendor/assets/javascripts/clipboard.js
- vendor/assets/swfs/ZeroClipboard.swf
Use clipboard.js instead of ZeroClipboard.
https://clipboardjs.com/
> Use clipboardjs

- app/assets/javascripts/infrastructures.js
- app/assets/javascripts/infrastructures/view-rules-tabpane.js
- app/assets/javascripts/modules/table_render.js
- app/controllers/nodes_controller.rb
- app/views/infrastructures/_security_groups_table.html.erb
ref: https://skyarch.backlog.jp/view/NC-621
> Sec bugfix

- config/application.rb
- doc/installation/skyhopper.md
Update process
----------
```sh
cd YOUR_SKYHOPPER_DIRECTORY
git pull
git checkout v1.15.2
```
> v1.15.2 update document release

- lib/erb-builder/templates/presets/Multi_DataCenter_Pattern_with_RDS.json.erb
Hi!
I and @sweep3092 found a typo yesterday. 
Please merge it :bow:
> Fix typo. DRS -> RDS

- app/models/rds.rb
I'll merge this once test is done.
> Updated the RDS instance type list

- lib/erb-builder/fragments/ami_mappings.rb
update API_mappings.rb for 2016.03 amazon linux release
> Update to AMI  2016.03

- Gemfile
- Gemfile.lock
Downgrade devise into stable version because it causes problems
> Use devise stable

- spec/controllers/zabbix_servers_controller_spec.rb
Applies code style fixes from an rubocop by [SideCI](https://sideci.com).
> Applied fixes from SideCI

- app/assets/javascripts/infrastructures.js
- app/assets/javascripts/projects.js
- app/views/infrastructures/index.html.erb
- app/views/projects/index.html.erb
- lib/erb-builder/fragments/ami_mappings_windows.rb
I'll merge this once test passed.
> Ami windows update

- app/assets/javascripts/infrastructures.js
- app/assets/javascripts/projects.js
- app/views/infrastructures/index.html.erb
- app/views/projects/index.html.erb
- lib/erb-builder/fragments/ami_mappings_windows.rb
Reverts skyarch-networks/skyhopper#286
> Revert "Ami windows update"

- app/jobs/server_state_worker.rb
- config/application.rb
Minor update. I'll merge this to current develop after test is done.
> Updated application settings to current version

- app/controllers/app_settings_controller.rb
- app/controllers/clients_controller.rb
Set after action on client index by syncing zabbix to current user
> Zabbix Client Sync

- app/assets/javascripts/app_settings.js
- app/assets/stylesheets/application.css
- app/assets/stylesheets/simple_sidebar.css
- app/views/app_settings/_panel_content_system.html.erb
- app/views/app_settings/show.html.erb
- app/views/layouts/_navbar_top.html.erb
- config/locales/en.yml
- config/locales/ja.yml
- Fix padding bottom specially when using different screen sizes
- Disable application logo links and language when pressing chef create button.
Please review and merge pr. @root-beer 🙇
> Aws padding fix

- bower.json
ref: https://skyarch.backlog.jp/view/NC-655
> Typechange ipam00303

- app/controllers/app_settings_controller.rb
- config/application.rb
App Setting Controller Authenticate USer except on chef creation
Direct fix. Needs to be merged immediately. @root-beer
> Auth Fix on App Controller

- app/controllers/nodes_controller.rb
ref: https://skyarch.backlog.jp/view/NC-640
> Fix problem during update_attributes

- Gemfile
- Gemfile.lock
- doc/installation/en/skyhopper.md
- doc/installation/skyhopper.md
Removed unused dependencies and downgrade net-http-persistent as it is still buggy
> Dependency Problems fix

- config/locales/ja.yml
ref: https://skyarch.backlog.jp/view/NC-668
> NC-668: Improve ja locale

- doc/installation/en/skyhopper.md
- doc/installation/skyhopper.md
- public/502.html
ref: https://skyarch.backlog.jp/view/NC-670
> Display custom error page on bad gateway

- app/models/s3.rb
this is a hotfix. that needs to be directly merged. to develop and it is a small commit.
ref: https://skyarch.backlog.jp/view/NC-680
> [FIX] NC-680

- app/assets/javascripts/infrastructures/ec2-tabpane.js
- app/views/infrastructures/modal/_modal_change_rules.html.erb
Renamed inconsistend method naming when checking if the method exists.
> [Fix] RDS Change Security Group Modal

- app/jobs/operation_worker.rb
* 運用スケジュールを設定したインスタンスが決められた時刻に停止されない問題を修正
> Fix operation worker

- app/assets/javascripts/modules/newVM.js
- app/views/infrastructures/_show.html.erb
- config/locales/en.yml
- config/locales/ja.yml
リソース表示画面で表示できるリソースがない場合でもリソースなし画面を表示する
> Display "no resource"

- app/controllers/servertests_controller.rb
- app/models/node.rb
- spec/models/node_spec.rb
Serverspecの結果の詳細ログを成否に関わらず出力するように変更
Serverspecの結果の詳細ログにsummary_line情報を追加
Serverspecの結果にpendingがあると正常に動作しないバグの修正
> Update servertest result log

- app/assets/javascripts/cf_templates.js
- app/assets/javascripts/infrastructures.js
- app/assets/javascripts/infrastructures/add-modify-tabpane.js
- app/assets/javascripts/modules/newVM.js
- app/controllers/cf_templates_controller.rb
- app/controllers/template_builder_controller.rb
- app/models/cf_template.rb
- app/validators/yaml_validator.rb
- app/views/cf_templates/_form.html.erb
- app/views/cf_templates/_show.html.erb
- app/views/vue/_add_modify_tabpane.html.erb
- config/locales/en.yml
- config/locales/ja.yml
- db/migrate/20180705035046_add_format_to_cf_template.rb
- db/schema.rb
- db/seeds.rb
- frontend/src/models/cf_template.ts
- spec/controllers/cf_templates_controller_spec.rb
- spec/factories/cf_templates.rb
- spec/models/cf_template_spec.rb
CloudFormationテンプレートでYAMLフォーマットに対応。
なお、Frontend側のYAMLパースエラーの確認処理は実装していない。
> Support for YAML format with CloudFormation template

- app/assets/javascripts/infrastructures/stack-events-table.js
- app/views/infrastructures/_show.html.erb
- app/views/vue/_stack_events_table.html
> Add sorting function to stack-events table

- app/assets/javascripts/cf_templates.js
- app/assets/javascripts/clients.js
- app/assets/javascripts/dishes.js
- app/assets/javascripts/infrastructures.js
- app/assets/javascripts/infrastructures/ec2-tabpane.js
- app/assets/javascripts/projects.js
- app/assets/javascripts/servertests.js
- app/assets/javascripts/user_index.js
- frontend/src/helper.ts
- frontend/src/serverspec-gen.ts
> Fixed javascript console error

- doc/installation/en/skyhopper.md
- doc/installation/skyhopper.md
インストールドキュメントのYarnのインストール手順を修正。
（npmからYarnをインストールするのは非推奨のため、インストール手順を修正しました。）
> Yarnのインストール手順を修正

- app/models/chef_server/deployment.rb
> インストールできない不具合の修正

- app/controllers/app_settings_controller.rb
- app/models/app_setting.rb
- app/models/chef_server/deployment.rb
- db/migrate/20181128083719_add_dummy_and_remove_fqdn_and_remove_server_name_to_app_setting.rb
- db/schema.rb
- spec/factories/app_settings.rb
- spec/models/app_setting_spec.rb
- spec/models/chef_server/deployment_spec.rb
app_setting周りをリファクタリング。
"SkyHopperのセットアップ"画面で、入力項目に"This is dummy!"と入力するとセットアップが完了しない機能を削除。
> app_setting周りをリファクタリング

- lib/tasks/release.rake
> release.rakeの内容をnpmからyarnに変更

- lib/tasks/release.rake
> release.rakeの内容からbowerを削除

- app/controllers/nodes_controller.rb
> インスタンスの設定画面が動作しない不具合の修正

- .eslintignore
- .eslintrc.json
- frontend/package.json
- frontend/yarn.lock
ESLintを追加します。
ルールについてはリファクタリングの時に変更していきます。
> Hello ESLint

- app/controllers/cf_templates_controller.rb
- app/libs/known_hosts.rb
- app/models/ec2_instance.rb
- app/models/stack.rb
CloudFormation展開時にknown_hostsにEC2インスタンスの鍵を登録します。
> CloudFormation展開時にknown_hostsにEC2インスタンスの鍵を登録する

- .gitignore
- app/assets/javascripts/infrastructures.js
- app/assets/javascripts/infrastructures/ec2-tabpane.js
- app/assets/javascripts/infrastructures/edit-ansible-playbook-tabpane.js
- app/assets/javascripts/models/ec2_instance.js
- app/assets/stylesheets/application.css
- app/controllers/nodes_controller.rb
- app/libs/ansible.rb
- app/models/node.rb
- app/models/resource.rb
- app/models/resource_status.rb
- app/policies/node_policy.rb
- app/views/infrastructures/_show.html.erb
- app/views/nodes/edit_ansible_playbook.jbuilder
- app/views/nodes/show.jbuilder
- app/views/vue/_ec2_tabpane.html.erb
- app/views/vue/_edit_ansible_playbook_tabpane.html.erb
- config/locales/en.yml
- config/locales/ja.yml
- config/routes.rb
- db/migrate/20190104063406_add_playbook_roles_and_extra_vers_to_resource.rb
- db/schema.rb
- doc/installation/en/skyhopper.md
- doc/installation/skyhopper.md
- spec/controllers/nodes_controller_spec.rb
- spec/models/node_spec.rb
- spec/models/resource_spec.rb
- spec/policies/node_policy_spec.rb
> Welcome ansible

- app/assets/javascripts/infrastructures/view-rules-tabpane.js
- app/views/layouts/application.html.erb
- config/initializers/assets.rb
- config/locales/en.js.yml
- config/locales/ja.js.yml
> JavaScriptのフォント読み込みを非同期に変更

- LICENSE
- app/views/layouts/_navbar_bottom.html.erb
> Copyrightの更新年を2019にアップデート

- app/controllers/cf_templates_controller.rb
- app/controllers/nodes_controller.rb
- app/controllers/servertests_controller.rb
- app/models/resource.rb
- config/locales/en.yml
- config/locales/ja.yml
- db/migrate/20190218035754_add_register_in_known_hosts_to_resource.rb
- db/schema.rb
- spec/controllers/nodes_controller_spec.rb
- spec/factories/resources.rb
Resourceモデルに”known_hostsに鍵が登録されたかどうかのフラグ”を追加しました。
> known_hostsに鍵が登録されたかどうかのフラグを追加

- app/controllers/resources_controller.rb
- spec/controllers/resources_controller_spec.rb
インフラストラクチャにEC2インスタンスを追加する時に、known_hostsに鍵を登録する処理を追加しました。
> EC2インスタンス追加時にknown_hostsに鍵を登録する処理を追加

- .gitignore
.gitignoreを整理しました。
.gitignoreにjQuery map fileを追加しました。
> .gitignoreを整理

- config/application.rb
> バージョン2.1.0の準備

- README.md
- README_EN.md
> README.mdの説明を修正

- app/helpers/application_helper.rb
- app/helpers/dishes_helper.rb
- app/helpers/infrastructures_helper.rb
- app/helpers/vue_helper.rb
- lib/erb-builder/erb-builder.rb
RubyコードをRubocopのルールにもとづき一部リファクタリングしました。
> Ruby部分をリファクタリング(Part4)

- .rubocop.yml
- .travis.yml
- app/helpers/application_helper.rb
- app/helpers/form_helper.rb
- app/helpers/template_builders_helper.rb
Rubocopのルールを変更しました。
RubyコードをRubocopのルールにもとづき一部リファクタリングしました。
travisの処理にrubocopを追加しました。
> Ruby部分をリファクタリング(Part5)

- app/helpers/application_helper.rb
> ヘッダーのmasterラベルのレイアウトを修正

- .eslintrc.json
- app/assets/javascripts/app_settings.js
- app/assets/javascripts/application.js
- app/assets/javascripts/cf_templates.js
- app/assets/javascripts/clients.js
- app/assets/javascripts/databases.js
- app/assets/javascripts/demo-grid.js
- app/assets/javascripts/dishes.js
- app/assets/javascripts/helper.js
- app/assets/javascripts/infrastructures/stack-events-table.js
- app/assets/javascripts/key_pairs.js
- app/assets/javascripts/modules/listen.js
- app/assets/javascripts/modules/loadindex.js
- app/assets/javascripts/modules/newVM.js
- app/assets/javascripts/modules/wrap.js
- app/assets/javascripts/projects.js
- app/assets/javascripts/resources.js
- app/assets/javascripts/server_status.js
- app/assets/javascripts/serverspec-gen.js
- app/assets/javascripts/servertests.js
- app/assets/javascripts/template_builder.js
- app/assets/javascripts/zabbix_servers.js
- app/assets/javascripts/zabbix_servers/zabbix_edit.js
- app/assets/javascripts/zabbix_servers/zabbix_index.js
ESLintのルールを変更しました。
JavaScriptコードをESLintのルールにもとづき一部リファクタリングしました。
> JavaScriptのリファクタリング(Part1)

- app/assets/javascripts/dishes.js
- app/helpers/dishes_helper.rb
- app/views/dishes/index.json.jbuilder
- app/views/vue/_ec2_tabpane.html.erb
Dish一覧画面の検証状態の表示がおかしい不具合の修正しました。
Dish一覧画面の更新ボタンを押すと、削除ボタンが有効になってしまう不具合を修正しました。
インフラ詳細画面のEC2タブのDish周りのUIの不具合を修正しました。
> Dish周りの不具合の修正

- app/assets/javascripts/infrastructures/helper.js
> JSONのエラー表示がおかしい不具合の修正

- app/views/zabbix_servers/index.json.jbuilder
ZabbixServer一覧画面の、ZabbixServerのリンクを修正しました。
> ZabbixServer一覧のリンクを修正

- app/models/zabbix.rb
ZabbixServerの編集でエラーが発生する不具合を修正しました。
> ZabbixServerの編集でエラーが発生する不具合の修正

- app/assets/javascripts/infrastructures/operation-sched-tabpane.js
- app/assets/javascripts/modules/datepicker.js
- app/views/infrastructures/modal/_modal_manage_schedule.html.erb
運用スケージュールのカレンダーに表示されるスケジュールの時間がおかしい不具合を修正しました。
運用スケージュールの設定画面の動作がおかしい不具合を修正しました。
> 運用スケージュールの画面の不具合の修正

- scripts/app_run.sh
Dockerでforemanが落ちたらappが落ちるように変更しました。
> Dockerでforemanが落ちたらappが落ちるように変更

- app/assets/javascripts/models/servertest.js
- app/assets/javascripts/serverspec-gen.js
- app/controllers/servertests_controller.rb
- app/views/servertests/generator.html.erb
Servertest一覧ですべてが表示されない不具合を修正しました。
Serverspecジェネレータ機能を復活させました。
> Servertests周りの修正

- app/assets/javascripts/clients.js
顧客一覧画面で顧客を削除したときに画面に即座に反映されない不具合を修正しました。
> 顧客一覧画面で顧客を削除したときに画面に即座に反映されない不具合を修正

- app/assets/javascripts/projects.js
案件一覧でZabbixサーバが落ちてる状態で案件を削除した際にエラーが表示されない不具合を修正しました。
案件一覧画面で案件を削除したときに画面に即座に反映されない不具合を修正しました。
> Projects周りの修正

- .travis.yml
> Update: travisの環境をbionicに変更(master)

- db/seeds.rb
> rake db:seedの冪等性ミスの修正

- app/views/vue/_index.html.erb
ユーザー一覧ページでコンソールにエラーが出ていたのを修正しました。
> ユーザー一覧ページでコンソールにエラーが出ていたのを修正

- app/assets/javascripts/infrastructures/ec2-tabpane.js
セキュリティグループの編集画面が表示されない不具合を修正しました。
> セキュリティグループの編集画面が表示されない不具合の修正

- app/controllers/cf_templates_controller.rb
- app/controllers/ec2_instances_controller.rb
- app/controllers/monitorings_controller.rb
- app/controllers/nodes_controller.rb
- app/controllers/project_parameters_controller.rb
- app/controllers/resources_controller.rb
- app/controllers/servertests_controller.rb
- app/controllers/template_builder_controller.rb
- config/locales/en.yml
- config/locales/ja.yml
- spec/controllers/ec2_instances_controller_spec.rb
- spec/controllers/server_status_controller_spec.rb
- spec/models/servertest_spec.rb
app/controllers/cf_templates_controller.rbの処理を一部修正
インスタンスタイプの変更で同じタイプを選んだ場合のステータスコードを変更
一部のメッセージをI18n化
コードのリファクタリングとテストの追加
> コードのTODOを一部解決

- amazonlinux2/Dockerfile
- lib/tasks/db.rake
Dockerでrake db:data:*が動くように変更しました。
> Dockerでrake db:data:*が動くように変更

- config/application.rb
- config/environments/production.rb
本番環境で起動しない不具合を修正しました。
バージョン番号を2.1.1に変更しました。
> [HOTFIX] 本番環境で起動しない不具合の修正(Version 2.1.1)

- config/application.rb
- config/environments/production.rb
> [HOTFIX] production環境で起動しない不具合の修正(develop)

- .travis.yml
travisのチェックが時々失敗するので、処理を修正しました。
> travisの処理を修正

- .travis.yml
- .travis/database.yml
- Gemfile
- Gemfile.lock
- config/database_default.yml
- config/database_docker.yml
- spec/models/server_state_spec.rb
- spec/spec_helper.rb
test環境で使用するDBをSQLite3からMySQLに変更しました。
> test環境で使用するDBをSQLite3からMySQLに変更

- doc/installation/en/skyhopper.md
- doc/installation/skyhopper.md
> インストール手順の修正

- app/controllers/databases_controller.rb
- app/models/database_manager.rb
> DBのインポートが動かない不具合を修正
