skyarch-networks/skyhopper

app/jobs/periodic_serverspec_job.rb
app/jobs/periodic_yum_job.rb
app/jobs/serverspec_job.rb
app/jobs/yum_job.rb

最新の`Sidekiq`で動くように対応しました。
私は`ActiveJob`周りに明るくないので、問題があったら教えて下さい
Ref
----
- https://github.com/mperham/sidekiq/issues/2424
- https://travis-ci.org/skyarch-networks/skyhopper/jobs/71870513

[FIX] not include Sidekiq::Worker into Job class with ActiveJob.

---

app/assets/javascripts/app_settings.js
app/controllers/app_settings_controller.rb
config/locales/en.yml
config/locales/ja.yml
spec/controllers/app_settings_controller_spec.rb

EIP の個数制限を Deploy Wizard で最初にデータを送った時に検証し、もし EIP が足りなければエラーを表示するようにしました。

Check EIP limit when deploy wizard.

---

app/controllers/cf_templates_controller.rb
spec/controllers/cf_templates_controller_spec.rb

Please merge this to next version. A hotfix for the pagination in cloudformation index page.

[Hotfix] remove backend pagination diverto to vue.js

---

app/models/ec2_instance.rb

- not have public_dns
- have elastic_ip
- have private_dns
There's an EC2 instance like the above in yunoki san's AWS 
Before this patch, When we call `fqdn` method for EC2 instance like the above, returns private_dns.
However, we want an elastic_ip.

Use EIP as FQDN

---

app/controllers/concerns/error_handler.rb

see: https://skyarch.backlog.jp/view/NC-555
We often encounter redirect loop after `git pull`.
In many case, cause is forgetting `bower intall`, `npm install`, `gulp ts`, ...
but this is confusing. so, prevent redirect-loop and show better_errors console.
@Joeper214  please review and merge :bow:

Prevent redirect loop when Sprockets::FileNotFound

---

Gemfile
Gemfile.lock

Still unstable version. I'll update this after a few months.
I'll merge this once done.

downgrade browserify rails becuase causing problems.

---

app/assets/stylesheets/application.css
config/environments/production.rb
doc/installation/skyhopper.md
public/fonts/glyphicons-halflings-regular.eot
public/fonts/glyphicons-halflings-regular.svg
public/fonts/glyphicons-halflings-regular.ttf
public/fonts/glyphicons-halflings-regular.woff
public/fonts/glyphicons-halflings-regular.woff2
vendor/assets/fonts/glyphicons-halflings-regular.eot
vendor/assets/fonts/glyphicons-halflings-regular.svg
vendor/assets/fonts/glyphicons-halflings-regular.ttf
vendor/assets/fonts/glyphicons-halflings-regular.woff

NC-585
Update process
------
Add the following code into server block of your nginx.conf .
```nginx
location ~ ^/(assets|fonts) {
root /home/pocke/ghq/github.com/skyarch-networks/skyhopper/public;
}
```
and restart nginx(e.g. `systemctl nginx restart`)
and restart SkyHopper
```sh
./scripts/skyhopper_daemon.sh stop
./scripts/skyhopper_daemon.sh start
```

Nginx serve assets

---

app/assets/javascripts/libraries.js

An error occurs because xray gem isn't loaded in production.
Xray insert itself into views automatically.
So `//= require xray` is not necessary.

Remove unnecessary require

---

db/seeds.rb

Ref: https://skyarch.backlog.jp/view/NC-590
When we re-run `rake db:seed`, SkyHopper delete cf-template history.
I fixed it.
@Joeper214 please review and merge it :bow:

Remove only non history cf-template when rake db:seed

---

app/assets/javascripts/infrastructures.js
app/assets/javascripts/infrastructures/add-modify-tabpane.js
app/assets/javascripts/infrastructures/helper.js
app/assets/javascripts/infrastructures/show_infra.js
app/assets/javascripts/infrastructures/stack-events-table.js
app/assets/javascripts/modules/newVM.js
app/views/infrastructures/_show.html.erb

Goal
---------
Next Goal
-------
- Split files other components
current_infra
--------
- グローバル変数から`current_infra`を消す
- 現在`current_infra`を必要としている component には、infra_id を prop として渡すようにする。
- `current_infra` に相当するものが必要になったら、`new Infrastructure(infra_id)`する
app
------
- グローバル変数から`app`を消す
- `app`に相当するものが必要になったら、`this.$parent`を参照する。
- あまりいい手ではない気がするけど、グローバル変数よりマシ

Refactor infra js

---

frontend/src/users_admin.ts

when running `$gulp ts` this error occurs during fresh install.
Solution:
- Added super constructor before accessing  constructor in typescript

admin.ts file

---

app/models/node.rb

If ~/.ssh does not exist, host key is not registered to ~/.ssh/known_hosts.

mkdir ~/.ssh if not exists

---

lib/erb-builder/fragments/ami_mappings.rb

Ref: Update to AMI 2016.03 #249

Correct Amazon Linux AMI ID mapping for preset tempates

---

app/controllers/app_settings_controller.rb

Error occurs when optional parameters (vpc_id, subnet_id) are not present.

Fix NC-672

---

app/views/vue/_edit_attr_tabpane.html.erb

Prevent update function from submiting default on firefox and chrome

Edit Attribute Firefox Bug

---

app/assets/javascripts/infrastructures/operation-sched-tabpane.js
app/assets/javascripts/modules/listen.js
app/models/node.rb
app/validators/ruby_validator.rb
app/views/dishes/_show.html.erb
app/views/servertests/_form.html.erb
app/views/servertests/edit.html.erb
app/views/servertests/generator.html.erb
app/views/servertests/new.html.erb
app/views/vue/_servertest_results_tabpane.html.erb

* String でない可能性があるオブジェクトを `+` メソッドで連結せずに、式展開を使って文字列を生成するように変更
* Servertests の結果表示で、servertest 項目が多数ある場合に見辛くなる問題を修正
* マークアップの修正と整形
* Servertests 関連の多数の箇所で正しい翻訳が表示されない問題を修正

Servertests Improvements

---

app/controllers/infrastructures_controller.rb
app/models/infrastructure.rb
spec/controllers/infrastructures_controller_spec.rb
spec/models/infrastructure_spec.rb

スタックのステータスがUPDATE_COMPLETEの場合にページをリロードするとリソースのステータスがUnExecutedに戻ってしまう不具合の修正

Fixed infrastructure resource status bug

---

.gitignore
app/assets/javascripts/infrastructures/view-rules-tabpane.js
app/assets/javascripts/modules/fonts_map.js
app/assets/javascripts/modules/ipam00303.js
app/assets/javascripts/modules/ipam00303.map.js
app/assets/javascripts/modules/vfs_fonts.js
bower.json
doc/installation/en/skyhopper.md
doc/installation/skyhopper.md
frontend/build_font.js
frontend/package.json

ChromeでセキュリティグループのPrintボタンが動作しなくなっていたのを修正
詳細
PDF生成に使用していたライブラリをpdfmake-browserifiedからpdfmakeに変更
pdfmakeで使用できるようにフォントをビルドするスクリプトを追加
PDF出力に使用しているフォントをよくわからないものからKaigen Fontsに変更

ChromeでセキュリティグループのPrintボタンが動作しなくなっていたのを修正

---

app/controllers/servertests_controller.rb

詳細
Servertest編集画面で送信ボタンを押したら、編集していたServertestのインフラストラクチャのServertest一覧画面に繊維するように修正

Servertest編集画面から送信ボタンを押したときの画面遷移がおかしい不具合を修正

---

.gitignore

gitignoreに/public/javascripts/i18n.jsを追加
/public/javascripts/i18n.jsは`rake i18n:js:export`で自動的に作成される。

gitignoreに/public/javascripts/i18n.jsを追加

---

app/assets/javascripts/app_settings.js
app/controllers/app_settings_controller.rb
app/controllers/projects_controller.rb
app/helpers/zabbix_servers_helper.rb
app/models/chef_server/deployment.rb
app/models/infrastructure.rb
app/models/project.rb
app/models/server_state.rb
app/views/app_settings/_panel_content_system.html.erb
app/views/projects/_form.html.erb
config/locales/en.yml
config/locales/ja.yml
spec/models/server_state_spec.rb

アプリセットアップ時にZabbixServerを作成しないオプションを追加。
案件作成時のZabbixServerの選択肢になしを追加。
ZabbixServerがなくても動作するように変更。

Zabbixの切り離し

---

app/controllers/nodes_controller.rb
app/views/nodes/show.jbuilder
app/views/vue/_ec2_tabpane.html.erb
config/locales/en.yml
config/locales/ja.yml
spec/controllers/nodes_controller_spec.rb

ChefServerが起動していなくても最低限の機能を使えるようにしました。
なお、今現在Dish周りの機能が動作しないためそちらは未改修となります。

ChefServerが起動していなくても最低限の機能を使えるようにする

---

README.md
README_EN.md
config/application.rb
doc/installation/en/skyhopper.md
doc/installation/skyhopper.md

SkyHopperのVersionを2に上げます。
Version2では、Chefの機能は削除され、Ansibleに置き換えられます。
Chefの機能の一部はまだ使える状態ですが、将来的には削除される予定です。

SkyHopperをVersion2にアップデート

---

lib/erb-builder/templates/zabbix_server.json.erb

ZabbixServerインストール時に非推奨のオプションを使用していたのを修正しました。

ZabbixServerインストール時に非推奨のオプションを使用していたのを修正

---

app/assets/javascripts/modules/newVM.js

インスタストラクチャ一覧画面で、「リソース有りのインフラ」→「リソース無しのインフラ」の順番に表示した場合に画面の表示がおかしい不具合の修正

インスタストラクチャの詳細画面の不具合を修正

---

docker-compose.override-mac-sample.yml
docker-compose.yml

Docker for macでVolumeのマウントが遅いのでキャッシュを有効にした

dockerでの起動の高速化

---

app/assets/javascripts/infrastructures/elb-tabpane.js

インフラストラクチャのELBタブでセキュリティグループのNameが表示されない不具合を修正しました。

インフラストラクチャのELBタブでセキュリティグループのNameが表示されない不具合の修正

---

app/assets/javascripts/infrastructures/view-rules-tabpane.js
app/assets/javascripts/models/ec2_instance.js

EC2周りの通信で、パラメータが正常に送信されていなかった不具合を修正しました。
インフラストラクチャのセキュリティグループを表示する画面で、セキュリティグループの表が表示されない不具合を修正しました。

EC2周りの通信の修正とセキュリティグループ周りの修正

---

app/assets/javascripts/models/infrastructure.js

リソースの作業履歴を単体でエクスポートできない不具合を修正しました。

リソースの作業履歴が単体でエクスポートできない不具合の修正

---

.travis.yml

Ubuntu14.04を明示的に使用するようにすることでエラーを回避する
14.04がEOLなので16.04で起こるエラーの修正ができ次第14.04の指定を消したほうがいいと思われます

Travis上でのビルド環境の変更によるエラーの一時的な修正

---

app/assets/javascripts/user_index.js
app/controllers/users_admin_controller.rb
app/views/users_admin/new.html.erb
config/locales/en.yml
config/locales/ja.yml

ユーザー作成時のZabbixサーバの選択を任意に変更しました。
ユーザー削除時に自分自身を削除しようとしたときにエラーメッセージを追加しました。
ユーザー削除時のZabbixサーバに対する処理がおかしい不具合を修正しました。

ユーザー管理機能の修正

---

doc/installation/en/skyhopper.md
doc/installation/skyhopper.md

jquery-uiのビルドに必要なため、インストール手順でnodeのバージョンを固定しました。

インストール手順でnodeのバージョンを固定

---

config/secrets.yml

secretsのdb_crypt_saltがdevelopment環境とtest環境で同じになっていたのを修正しました。

secretsのdb_crypt_saltがdevelopment環境とtest環境で同じになっていたのを修正

---

app/controllers/databases_controller.rb
app/models/database_manager.rb
app/views/databases/_modal_export.html.erb
config/locales/en.yml
config/locales/ja.yml
lib/tasks/db.rake

DBのエクスポートに非互換性オプションを追加しました。
DBのエクスポート時に、”互換性を維持しない”にチェックを入れてエクスポートすると、mysqldump時の `--compatible=ansi` の指定が解除されます。
”互換性を維持しない”のチェックを外してエクスポートすると、今までと同じ挙動になります。

DBのエクスポートに非互換性オプションを追加

---

.gitignore
app/assets/javascripts/infrastructures/ec2-tabpane.js
app/assets/javascripts/models/ec2_instance.js
app/controllers/cf_templates_controller.rb
app/controllers/nodes_controller.rb
app/controllers/resources_controller.rb
app/libs/known_hosts.rb
app/models/ec2_instance.rb
app/models/resource.rb
app/models/stack.rb
app/policies/node_policy.rb
app/views/infrastructures/modal/_modal_register_for_known_hosts.html.erb
app/views/vue/_ec2_tabpane.html.erb
config/locales/en.yml
config/locales/ja.yml
config/routes.rb
db/migrate/20191108072820_remove_register_in_known_hosts_to_resource.rb
db/schema.rb
doc/docker.md
docker-compose.yml
spec/controllers/nodes_controller_spec.rb
spec/controllers/servertests_controller_spec.rb
spec/factories/resources.rb
spec/policies/node_policy_spec.rb

@@@ NOTICE @@@
known_hostsをハッシュ化している環境では、このアップデートを適用すると正常に動作しなくなる可能性があります。
現時点でSkyHopperがサポートしているAmazonLinux(ver1)での動作は確認致しました。
@@@@@@@@@@
known_hostsにEC2の鍵を登録するボタンを追加しました。
Ansible、yum、Servertest実行時に、known_hostsにリモートホストの鍵が登録されているか確認する処理を、"DBのフラグで確認"から"実際に取得して確認"に変更しました。
CloudFormationテンプレート展開完了時に、known_hostsに鍵を登録する処理を削除しました。
Dockerを使用している場合は、下記のコマンドを実行する必要があります。
```
mv amazonlinux2/known_hosts amazonlinux2/.ssh/
```

known_hostsファイルの管理方法の変更
